### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by jjensn** [GregoryDosh/Home-Assistant-DreamScreen-Service#2]
I literally just finished plugging mine in and sent an e-mail to support asking for the API reference so I could do a home-assistant integration. Looks like you beat me to it.

Nice work and thanks !

**Comment by GregoryDosh** [comment]
Thanks, much appreciated.  It was something I wanted to do myself since I have multiple HDMI switchers into my DreamScreen and was a little frustrated with not being able to automate switching between all my sources appropriately.  If you find something lacking let me know or feel free to submit a PR.  This was my first pass at something useable.

**Comment by jjensn** [comment]
I am working on reverse engineering the UDP protocol so that I can get statuses. The forum post where the packet schema is posted hints that it may be possible. If I find anything I'll let you know

**Comment by GregoryDosh** [comment]
That would be great.  If I get around to it I might poke around myself.  There must be more available to pull/change since the Android & iPhone app can change more than just what their spec shows.  In brute forcing the packets I was able to accidentally change settings such as zone toggles or CEC and other things it seemed but I wasn't sure of what was what since I basically just did brute force to see what might happen.  Their must be some sort of response back from the DreamScreen giving status but I haven't looked into reverse engineering the Android app or the UDP protocol itself since I'm less knowledgeable in those areas.
