### ISSUE TITLE
GitHub returned 404 when updating through HACS

### ISSUE THREAD

**Issue by DrmeddieWiese** [GregoryDosh/Home-Assistant-DreamScreen-Service#31]
Hello,

following error occurred while updating the DreamScreen Service:

```
An error ocoured while processing
GitHub returned 404 for https://api.github.com/repos/GregoryDosh/Home-Assistant-DreamScreen-Service/contents//manifest.json
```

Reinstallation is no longer possible via HACS due to the missing manifest.json

HACS | 0.21.6
System | HassOS 3.11
HomeAssistant  |  0.106.3

**Comment by J3n50m4t** [comment]
Could you try uninstalling the current dream screen component and restart HA and then install it again? 
After these steps I'm able to use the reinstall. 
I guess its because of moved manifest files in  commit https://github.com/GregoryDosh/Home-Assistant-DreamScreen-Service/commit/4c672c3c8e22ee246cc7e74190895b785754275c

**Comment by J3n50m4t** [comment]
Pinned, because this will probably happen to to all HACS Users. I'm sorry, but we now use the correct HACS folder structure, as HACS recommends

**Comment by DrmeddieWiese** [comment]
Thanks a uninstall, reboot and new install helped.
Work like a charm.
